# Generated by Django 2.2.28 on 2024-11-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20241116_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
